info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
dataSource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  username: user
  password: '123'
  pooled: true
  jmxExport: true
  url: jdbc:sqlserver:// 192.168.18.25:1433;databaseName=store;encrypt=true;trustServerCertificate=true

cors:
  enabled: true
  allowedOrigins:
    - https://simple-books-api.glitch.me/books
  allowedMethods:
    - GET
    - POST
environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:sqlserver:// 192.168.18.25:1433;databaseName=store;encrypt=true;trustServerCertificate=true
  test:
    dataSource:
      dbCreate: update
      url: jdbc:sqlserver:// 192.168.18.25:1433;databaseName=store;encrypt=true;trustServerCertificate=true
  production:
    dataSource:
      dbCreate: none
      url: jdbc:sqlserver:// 192.168.18.25:1433;databaseName=store;encrypt=true;trustServerCertificate=true
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
grails:
  codegen:
    defaultPackage: com.example
  profile: web
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html